project_id = "tvsdbztjqksxybxjwtrf"

[functions.sync-project]
verify_jwt = false

[functions.geocode-city]
verify_jwt = false

[functions.create-customer]
verify_jwt = true

[functions.seed-demo-data]
verify_jwt = true