-- Verwijder het incorrecte Hersenstichting project (ID 1001)
DELETE FROM public.projects WHERE basicall_project_id = 1001;

-- Voeg de 27 nieuwe projecten toe
INSERT INTO public.projects (name, project_key, basicall_project_id, basicall_token, is_active, hourly_rate, vat_rate, mapping_config)
VALUES
  ('ANBO Tipgids', 'anbo-tipgids', 827, 'placeholder_token', true, 35.00, 21, '{"freq_col": "frequentie", "freq_map": {"mnd": 12, "jaar": 1, "maand": 12, "eenmalig": 1, "kwartaal": 4, "jaarlijks": 1, "maandelijks": 12}, "amount_col": "termijnbedrag", "reason_col": "opzegreden", "sale_results": ["Sale", "Donateur", "Toezegging"]}'::jsonb),
  ('Bop Pitstop', 'bop-pitstop', 908, 'placeholder_token', true, 35.00, 21, '{"freq_col": "frequentie", "freq_map": {"mnd": 12, "jaar": 1, "maand": 12, "eenmalig": 1, "kwartaal": 4, "jaarlijks": 1, "maandelijks": 12}, "amount_col": "termijnbedrag", "reason_col": "opzegreden", "sale_results": ["Sale", "Donateur", "Toezegging"]}'::jsonb),
  ('De Limburgse Kluis', 'de-limburgse-kluis', 899, 'placeholder_token', true, 35.00, 21, '{"freq_col": "frequentie", "freq_map": {"mnd": 12, "jaar": 1, "maand": 12, "eenmalig": 1, "kwartaal": 4, "jaarlijks": 1, "maandelijks": 12}, "amount_col": "termijnbedrag", "reason_col": "opzegreden", "sale_results": ["Sale", "Donateur", "Toezegging"]}'::jsonb),
  ('Duramotion', 'duramotion', 900, 'placeholder_token', true, 35.00, 21, '{"freq_col": "frequentie", "freq_map": {"mnd": 12, "jaar": 1, "maand": 12, "eenmalig": 1, "kwartaal": 4, "jaarlijks": 1, "maandelijks": 12}, "amount_col": "termijnbedrag", "reason_col": "opzegreden", "sale_results": ["Sale", "Donateur", "Toezegging"]}'::jsonb),
  ('EO Eenmalig naar Structureel', 'eo-eenmalig-naar-structureel', 909, 'placeholder_token', true, 35.00, 21, '{"freq_col": "frequentie", "freq_map": {"mnd": 12, "jaar": 1, "maand": 12, "eenmalig": 1, "kwartaal": 4, "jaarlijks": 1, "maandelijks": 12}, "amount_col": "termijnbedrag", "reason_col": "opzegreden", "sale_results": ["Sale", "Donateur", "Toezegging"]}'::jsonb),
  ('Fysio-Match', 'fysio-match', 906, 'placeholder_token', true, 35.00, 21, '{"freq_col": "frequentie", "freq_map": {"mnd": 12, "jaar": 1, "maand": 12, "eenmalig": 1, "kwartaal": 4, "jaarlijks": 1, "maandelijks": 12}, "amount_col": "termijnbedrag", "reason_col": "opzegreden", "sale_results": ["Sale", "Donateur", "Toezegging"]}'::jsonb),
  ('Fysiomatch outbound', 'fysiomatch-outbound', 910, 'placeholder_token', true, 35.00, 21, '{"freq_col": "frequentie", "freq_map": {"mnd": 12, "jaar": 1, "maand": 12, "eenmalig": 1, "kwartaal": 4, "jaarlijks": 1, "maandelijks": 12}, "amount_col": "termijnbedrag", "reason_col": "opzegreden", "sale_results": ["Sale", "Donateur", "Toezegging"]}'::jsonb),
  ('Hersenstichting bestellers', 'hersenstichting-bestellers', 869, 'placeholder_token', true, 35.00, 21, '{"freq_col": "frequentie", "freq_map": {"mnd": 12, "jaar": 1, "maand": 12, "eenmalig": 1, "kwartaal": 4, "jaarlijks": 1, "maandelijks": 12}, "amount_col": "termijnbedrag", "reason_col": "opzegreden", "sale_results": ["Sale", "Donateur", "Toezegging"]}'::jsonb),
  ('Hersenstichting inbound', 'hersenstichting-inbound', 849, 'placeholder_token', true, 35.00, 21, '{"freq_col": "frequentie", "freq_map": {"mnd": 12, "jaar": 1, "maand": 12, "eenmalig": 1, "kwartaal": 4, "jaarlijks": 1, "maandelijks": 12}, "amount_col": "termijnbedrag", "reason_col": "opzegreden", "sale_results": ["Sale", "Donateur", "Toezegging"]}'::jsonb),
  ('Hersenstichting Storno', 'hersenstichting-storno', 539, 'placeholder_token', true, 35.00, 21, '{"freq_col": "frequentie", "freq_map": {"mnd": 12, "jaar": 1, "maand": 12, "eenmalig": 1, "kwartaal": 4, "jaarlijks": 1, "maandelijks": 12}, "amount_col": "termijnbedrag", "reason_col": "opzegreden", "sale_results": ["Sale", "Donateur", "Toezegging"]}'::jsonb),
  ('Inbound opvang', 'inbound-opvang', 500, 'placeholder_token', true, 35.00, 21, '{"freq_col": "frequentie", "freq_map": {"mnd": 12, "jaar": 1, "maand": 12, "eenmalig": 1, "kwartaal": 4, "jaarlijks": 1, "maandelijks": 12}, "amount_col": "termijnbedrag", "reason_col": "opzegreden", "sale_results": ["Sale", "Donateur", "Toezegging"]}'::jsonb),
  ('KIA samen tegen armoede', 'kia-samen-tegen-armoede', 807, 'placeholder_token', true, 35.00, 21, '{"freq_col": "frequentie", "freq_map": {"mnd": 12, "jaar": 1, "maand": 12, "eenmalig": 1, "kwartaal": 4, "jaarlijks": 1, "maandelijks": 12}, "amount_col": "termijnbedrag", "reason_col": "opzegreden", "sale_results": ["Sale", "Donateur", "Toezegging"]}'::jsonb),
  ('NL Tour Rides', 'nl-tour-rides', 901, 'placeholder_token', true, 35.00, 21, '{"freq_col": "frequentie", "freq_map": {"mnd": 12, "jaar": 1, "maand": 12, "eenmalig": 1, "kwartaal": 4, "jaarlijks": 1, "maandelijks": 12}, "amount_col": "termijnbedrag", "reason_col": "opzegreden", "sale_results": ["Sale", "Donateur", "Toezegging"]}'::jsonb),
  ('Proefdiervrij storno', 'proefdiervrij-storno', 11, 'placeholder_token', true, 35.00, 21, '{"freq_col": "frequentie", "freq_map": {"mnd": 12, "jaar": 1, "maand": 12, "eenmalig": 1, "kwartaal": 4, "jaarlijks": 1, "maandelijks": 12}, "amount_col": "termijnbedrag", "reason_col": "opzegreden", "sale_results": ["Sale", "Donateur", "Toezegging"]}'::jsonb),
  ('Proefdiervrij Upgrade', 'proefdiervrij-upgrade', 625, 'placeholder_token', true, 35.00, 21, '{"freq_col": "frequentie", "freq_map": {"mnd": 12, "jaar": 1, "maand": 12, "eenmalig": 1, "kwartaal": 4, "jaarlijks": 1, "maandelijks": 12}, "amount_col": "termijnbedrag", "reason_col": "opzegreden", "sale_results": ["Sale", "Donateur", "Toezegging"]}'::jsonb),
  ('Proefdiervrij winback', 'proefdiervrij-winback', 759, 'placeholder_token', true, 35.00, 21, '{"freq_col": "frequentie", "freq_map": {"mnd": 12, "jaar": 1, "maand": 12, "eenmalig": 1, "kwartaal": 4, "jaarlijks": 1, "maandelijks": 12}, "amount_col": "termijnbedrag", "reason_col": "opzegreden", "sale_results": ["Sale", "Donateur", "Toezegging"]}'::jsonb),
  ('Save the Children WB 2020', 'save-the-children-wb-2020', 540, 'placeholder_token', true, 35.00, 21, '{"freq_col": "frequentie", "freq_map": {"mnd": 12, "jaar": 1, "maand": 12, "eenmalig": 1, "kwartaal": 4, "jaarlijks": 1, "maandelijks": 12}, "amount_col": "termijnbedrag", "reason_col": "opzegreden", "sale_results": ["Sale", "Donateur", "Toezegging"]}'::jsonb),
  ('Sligro B2B', 'sligro-b2b', 889, 'placeholder_token', true, 35.00, 21, '{"freq_col": "frequentie", "freq_map": {"mnd": 12, "jaar": 1, "maand": 12, "eenmalig": 1, "kwartaal": 4, "jaarlijks": 1, "maandelijks": 12}, "amount_col": "termijnbedrag", "reason_col": "opzegreden", "sale_results": ["Sale", "Donateur", "Toezegging"]}'::jsonb),
  ('Sligro tintelingen', 'sligro-tintelingen', 870, 'placeholder_token', true, 35.00, 21, '{"freq_col": "frequentie", "freq_map": {"mnd": 12, "jaar": 1, "maand": 12, "eenmalig": 1, "kwartaal": 4, "jaarlijks": 1, "maandelijks": 12}, "amount_col": "termijnbedrag", "reason_col": "opzegreden", "sale_results": ["Sale", "Donateur", "Toezegging"]}'::jsonb),
  ('STC giftgevers', 'stc-giftgevers', 864, 'placeholder_token', true, 35.00, 21, '{"freq_col": "frequentie", "freq_map": {"mnd": 12, "jaar": 1, "maand": 12, "eenmalig": 1, "kwartaal": 4, "jaarlijks": 1, "maandelijks": 12}, "amount_col": "termijnbedrag", "reason_col": "opzegreden", "sale_results": ["Sale", "Donateur", "Toezegging"]}'::jsonb),
  ('STC storno', 'stc-storno', 904, 'placeholder_token', true, 35.00, 21, '{"freq_col": "frequentie", "freq_map": {"mnd": 12, "jaar": 1, "maand": 12, "eenmalig": 1, "kwartaal": 4, "jaarlijks": 1, "maandelijks": 12}, "amount_col": "termijnbedrag", "reason_col": "opzegreden", "sale_results": ["Sale", "Donateur", "Toezegging"]}'::jsonb),
  ('STC WB 6 maanden', 'stc-wb-6-maanden', 907, 'placeholder_token', true, 35.00, 21, '{"freq_col": "frequentie", "freq_map": {"mnd": 12, "jaar": 1, "maand": 12, "eenmalig": 1, "kwartaal": 4, "jaarlijks": 1, "maandelijks": 12}, "amount_col": "termijnbedrag", "reason_col": "opzegreden", "sale_results": ["Sale", "Donateur", "Toezegging"]}'::jsonb),
  ('STC WB Mailgroep', 'stc-wb-mailgroep', 905, 'placeholder_token', true, 35.00, 21, '{"freq_col": "frequentie", "freq_map": {"mnd": 12, "jaar": 1, "maand": 12, "eenmalig": 1, "kwartaal": 4, "jaarlijks": 1, "maandelijks": 12}, "amount_col": "termijnbedrag", "reason_col": "opzegreden", "sale_results": ["Sale", "Donateur", "Toezegging"]}'::jsonb),
  ('Test project', 'test-project', 837, 'placeholder_token', true, 35.00, 21, '{"freq_col": "frequentie", "freq_map": {"mnd": 12, "jaar": 1, "maand": 12, "eenmalig": 1, "kwartaal": 4, "jaarlijks": 1, "maandelijks": 12}, "amount_col": "termijnbedrag", "reason_col": "opzegreden", "sale_results": ["Sale", "Donateur", "Toezegging"]}'::jsonb),
  ('Tintelingen B2B outbound', 'tintelingen-b2b-outbound', 873, 'placeholder_token', true, 35.00, 21, '{"freq_col": "frequentie", "freq_map": {"mnd": 12, "jaar": 1, "maand": 12, "eenmalig": 1, "kwartaal": 4, "jaarlijks": 1, "maandelijks": 12}, "amount_col": "termijnbedrag", "reason_col": "opzegreden", "sale_results": ["Sale", "Donateur", "Toezegging"]}'::jsonb),
  ('Triple Tree', 'triple-tree', 893, 'placeholder_token', true, 35.00, 21, '{"freq_col": "frequentie", "freq_map": {"mnd": 12, "jaar": 1, "maand": 12, "eenmalig": 1, "kwartaal": 4, "jaarlijks": 1, "maandelijks": 12}, "amount_col": "termijnbedrag", "reason_col": "opzegreden", "sale_results": ["Sale", "Donateur", "Toezegging"]}'::jsonb),
  ('Trombosestichting folder', 'trombosestichting-folder', 761, 'placeholder_token', true, 35.00, 21, '{"freq_col": "frequentie", "freq_map": {"mnd": 12, "jaar": 1, "maand": 12, "eenmalig": 1, "kwartaal": 4, "jaarlijks": 1, "maandelijks": 12}, "amount_col": "termijnbedrag", "reason_col": "opzegreden", "sale_results": ["Sale", "Donateur", "Toezegging"]}'::jsonb),
  ('TTC marktonderzoek', 'ttc-marktonderzoek', 897, 'placeholder_token', true, 35.00, 21, '{"freq_col": "frequentie", "freq_map": {"mnd": 12, "jaar": 1, "maand": 12, "eenmalig": 1, "kwartaal": 4, "jaarlijks": 1, "maandelijks": 12}, "amount_col": "termijnbedrag", "reason_col": "opzegreden", "sale_results": ["Sale", "Donateur", "Toezegging"]}'::jsonb);